<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All requirements' => 'Усі потреби',
    'Create' => 'Додати',
    'Create Doctor' => 'Додата лікаря',
    'Create Hospital' => 'Додати лікарню',
    'Create Requirement' => 'Додати потребу',
    'Create Supplier' => 'Додати постачальника',
    'Created At' => 'Створено',
    'Delete' => 'Видалити',
    'Doctor' => 'Лікар',
    'Doctors' => 'Лікарі',
    'Done' => 'Виконано',
    'General information' => 'Загальна інформація',
    'Hospital ID' => 'Лікарня',
    'Hospitals' => 'Лікарні',
    'Hospitals requirements' => 'Потреби лікарень',
    'Human resources' => 'Ресурси',
    'I want to be a reserve doctor' => 'Я хочу бути лікарем резерву',
    'I want to be a volunteer' => 'Я хочу бути волонтером',
    'I\'m benefactor' => 'Я благодійник',
    'In Progress' => 'В процесі',
    'Join the fight' => 'Доєднатись до боротьби',
    'Khmelnitsky: COVID-19 Coronavirus Control Requirements' => 'Хмельницький: COVID-19 Потреби у засобах боротьби з коронавірусом',
    'List' => 'Список',
    'List of suppliers' => 'Перелік постачальників',
    'NA' => 'Не вказано',
    'Name' => 'Назва',
    'New' => 'Новий',
    'On moderation' => 'На модерації',
    'Published' => 'Опубліковано',
    'Register as a vendor' => 'Зареєструватись, як постачальник',
    'Requirements' => 'Потреби',
    'Requirements of hospital' => 'Потреби лікарні',
    'Search' => 'Пошук',
    'Send' => 'Надіслати',
    'Status' => 'Статус',
    'Supplier' => 'Постачальник',
    'Suppliers' => 'Постачальники',
    'Update' => 'Оновити',
    'Update Doctor' => 'Оновленя даних лікаря',
    'Update Hospital: ' => 'Редагування даних лікарні: ',
    'Update Requirement: ' => 'Редагування потреби: ',
    'Update Supplier' => 'Редагування постачальника',
    'Updated At' => 'Оновлено',
    'Your request has been processed successfully' => 'Ваша заявка успішно оформленна',
    'Benefactor' => 'Благодійник',
    'Benefactors' => 'Благодійники',
    'Create Benefactor' => 'Додати благодійника',
    'Create Volunteer' => 'Додати волонтера',
    'Update Benefactor' => 'Редагування даних благодійника',
    'Update Volunteer' => 'Редагування даних волонтера',
    'Volunteer' => 'Волонтер',
    'Volunteers' => 'Волонтери',
    'Dashboard' => 'Панель керування',
];
